//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameShopProg.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilyView
    {
        public int IDParent { get; set; }
        public int IPKid { get; set; }
        public bool IsAccepted { get; set; }
        public bool IsFullBan { get; set; }
        public bool IsTemporaryBan { get; set; }
        public Nullable<System.DateTime> BanEnd { get; set; }
        public int DailyLimitInMinutes { get; set; }
        public bool AccessFamilyLibrary { get; set; }
    
        public virtual User Parent { get; set; }
        public virtual User Kid { get; set; }
    }
}
